alphagov/govuk-mobile-backend

.github/workflows/sam-app-post-merge.yaml
.gitignore

[PSREDEV-XXX]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

fix: wrong bucket secret

---

nx.json
package-lock.json
package.json
tsconfig.base.json
tsconfig.json

nx workspace config for basic typescript workspace

---

README.md
nx.json
package-lock.json
package.json
tsconfig.json

GOVUKAPP-1428
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

Added basic typescript package and readme instructions

---

sam-app/feature-tests/vitest-features/GovUKMobileCognitoUserPool.feature
sam-app/feature-tests/vitest-step-definitions/GovUKMobileCognitoUserPool.steps.ts
sam-app/package-lock.json
sam-app/package.json
sam-app/template.yaml
sam-app/tsconfig.json
sam-app/vitest.config.ts

[GOVAPP-1424]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

feat: add basic cognito user pool to template.yaml

---

sam-app/feature-tests/vitest-features/GovUKMobileApiGateway.feature
sam-app/feature-tests/vitest-step-definitions/GovUKMobileApiGateway.steps.ts
sam-app/feature-tests/vitest-step-definitions/GovUKMobileCognitoUserPool.steps.ts
sam-app/feature-tests/vitest-step-definitions/GovUKMobileCognitoWAFAssociation.steps.ts
sam-app/feature-tests/vitest-step-definitions/GovUKMobileResourceTags.steps.ts
sam-app/feature-tests/vitest-step-definitions/GovUKMobileWebApplicationFirewall.steps.ts
sam-app/package-lock.json
sam-app/package.json
sam-app/template.yaml

[GOVAPP-1430]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

chore: basic api gateway for SAM template

---

.github/workflows/sam-app-post-merge.yaml
.gitignore

Unable to trigger deployment to build env
https://govukverify.atlassian.net/browse/GOVUKAPP-1471

Bug GOVUKAPP-1471 : Unable to trigger deployment to build env

---

.github/workflows/sam-app-deploy-via-env-secrets.yaml
sam-app/template.yaml

[PSREDEV-1430]
[PSREDEV-1430]: https://govukverify.atlassian.net/browse/PSREDEV-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add new build to include env secrets

---

.github/workflows/sam-app-deploy-via-env-secrets.yaml

[PSREDEV-1430]
[PSREDEV-1430]: https://govukverify.atlassian.net/browse/PSREDEV-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add new build

---

.github/workflows/auth-post-merge.yaml

Setting up DEV env and option to deploy to different environments
Ticket number
https://govukverify.atlassian.net/browse/GOVUKAPP-1443

GOVUKAPP-1443: Setting up DEV env and option to deploy to different environments

---

auth/feature-tests/infrastructure/features/UserPoolIdentityProvider.feature
auth/feature-tests/infrastructure/step-definitions/ResourceTags.steps.ts
auth/feature-tests/infrastructure/step-definitions/UserPoolIdentityProvider.steps.ts
auth/template.yaml

Adds AWS::Cognito::UserPoolIdentityProvider resource for OIDC
[GOVUKAPP-1484]
[GOVUKAPP-1484]: https://govukverify.atlassian.net/browse/GOVUKAPP-1484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add OIDC provider for onelogin

---

auth/feature-tests/infrastructure/features/ApiGateway.feature
auth/feature-tests/infrastructure/features/AttestationFunction.feature
auth/feature-tests/infrastructure/features/CognitoUserPool.feature
auth/feature-tests/infrastructure/features/CognitoWAFAssociation.feature
auth/feature-tests/infrastructure/features/PostAuthenticationFunction.feature
auth/feature-tests/infrastructure/features/UserPoolIdentityProvider.feature
auth/feature-tests/infrastructure/features/WebApplicationFirewall.feature
auth/feature-tests/infrastructure/step-definitions/ApiGateway.steps.ts
auth/feature-tests/infrastructure/step-definitions/CognitoUserPool.steps.ts
auth/feature-tests/infrastructure/step-definitions/CognitoWAFAssociation.steps.ts
auth/feature-tests/infrastructure/step-definitions/PostAuthenticationFunction.steps.ts
auth/feature-tests/infrastructure/step-definitions/UserPoolIdentityProvider.steps.ts
auth/feature-tests/infrastructure/step-definitions/WebApplicationFirewall.steps.ts

Remove unnessecary GOV UK text from tests

chore: remove gov uk text

---

.cz.toml
.gitignore
.pre-commit-config.yaml
CHANGELOG.md.j2
README.md
auth/vitest.config.ts
package-lock.json
package.json
pre-commit.sh
vitest.config.ts

Pre-Commit Hook

---

README.md

scope: Developer experience
description: Added basic instructions on how to install and use commitizen
footer:
JIRA-ID:GOVUKAPP-1490:

doc  commitizen instructions

---

auth/template.yaml

scope: infra
description: issue with erroneous lines in the template.yaml causing an issue with the deployment using `sam deploy`
footer:
JIRA-ID:GOVUKAPP-1484:

bug :boom: template.yaml deployment issue

---

.github/workflows/auth-post-merge.yaml
.github/workflows/ci.yaml

scope: ci
description: add `sam validate --lint` to ci to catch issues with template.yaml early

feat  add sam validate to ci

---

auth/package.json
auth/project.json
auth/tests/unit/cognito-ipd.unit.test.ts

scope: unit tests
description: Unit tests for AWS::Cognito::UserPoolIdentityProvider to enusre all properties are set properly
footer:
JIRA-ID:GOVUKAPP-1513:

refactor: add unit tests for aws::cognito::userpoolidentityprovider

---

auth/template.yaml
auth/tests/unit/cognito-ipd.unit.test.ts
auth/tests/unit/cognito-waf-log-group-kms-key.unit.test.ts
auth/tests/unit/cognito-waf-log-group.unit.test.ts
auth/tests/unit/cognito-waf-logging-configuration.unit.test.ts
auth/tests/unit/cognito-waf.unit.test.ts
auth/tests/unit/cognito-web-acl-association.unit.test.ts

scope: unit tests
description: Add new unit tests for template.yaml to cover the cognito waf and associated resources
footer:
JIRA-ID:GOVUKAPP-1608:

refactor  unit tests for cognito waf and associated resources

---

auth/template.yaml
auth/tests/unit/cognito-waf.unit.test.ts

scope: cognito waf
description: update to the name of the waf that's associated with cognito to make the concern clear
JIRA-ID:GOVUKAPP-1427:

config  change name of waf to reflect it's serving cognito

---

auth/tests/unit/cognito-client-oidc.unit.test.ts

Adding infra unit tests and addressing the review comments
https://govukverify.atlassian.net/browse/GOVUKAPP-1425

Adding infra unit tests

---

auth/template.yaml
auth/tests/unit/cognito-client-oidc.unit.test.ts
auth/tests/unit/cognito-ipd.unit.test.ts
auth/tests/unit/cognito-waf-log-group-kms-key.unit.test.ts
auth/tests/unit/cognito-waf-log-group.unit.test.ts
auth/tests/unit/cognito-waf-logging-configuration.unit.test.ts
auth/tests/unit/cognito-waf.unit.test.ts
auth/tests/unit/cognito-web-acl-association.unit.test.ts

Unit test for Cognito pool client
https://govukverify.atlassian.net/browse/GOVUKAPP-1425

Adding infra unit test

---

auth/template.yaml
auth/tests/unit/cognito-client-oidc.unit.test.ts
auth/tests/unit/cognito-ipd.unit.test.ts

feat  updates to the cognito oidc client for onelogin
scope: onelogin integration
description: Changes to the cognito user pool client to point to onelogin for the idp
JIRA-ID:GOVUKAPP-1567:

feat  updates to the cognito oidc client for onelogin

---

auth/template.yaml
auth/tests/unit/cognito-client-oidc.unit.test.ts
auth/tests/unit/cognito-custom-domain.unit.test.ts

scope: Cognito User Pool Domain
description: Adds a custom domain to the cognito user pool, configured per environment
footer:
JIRA-ID:GOVUKAPP-1567:

feat  add custom domain for cognito user pool

---

.github/workflows/auth-post-merge.yaml

* Matrix values should be the key names instead of the secret values

fix: use key names in matrix config to index into secrets values

---

auth/template.yaml

scope: cognito custom domains
description: fix typo in custom domains
footer:
JIRA-ID:GOVUKAPP-1567

config  fix typo in customdomain > environments

---

.github/workflows/auth-post-merge-dev.yaml

reverts: https://github.com/alphagov/govuk-mobile-backend/pull/66/files
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

fix: revert merging deployments

---

auth/feature-tests/functional/README.md
auth/feature-tests/functional/step-definitions/cognito-rate-limit-protection.steps.ts
auth/feature-tests/functional/step-definitions/middleware.steps.ts
auth/feature-tests/functional/step-definitions/token.steps.ts
auth/package.json
auth/project.json
auth/template.yaml
auth/tests/acc/cognito-client-oidc.test.ts
auth/tests/unit/cognito-client-oidc.unit.test.ts
auth/vitest.workspace.ts

scope: one login logout
description: sets the allowed logout url which uses the One Login /logout endpoint
footer:
JIRA-ID:GOVUKAPP-1532:

feat  logout url for cognito client

---

auth/package-lock.json
auth/package.json
auth/template.yaml
auth/tests/acc/cognito-client-oidc.test.ts
auth/tests/acc/cognito-post-authentication-lambda.test.ts
auth/tests/common/config.ts
auth/tests/unit/attestation.unit.test.ts
auth/tests/unit/cognito-post-authentication-lambda.unit.test.ts

scope: IAM
description: Added AWS::Lambda::Permission between Cognito IDP and PostAuthentication Function
footer: closes 1656
JIRA-ID:GOVUKAPP-1656

bug  cognito -> lambda permission issue

---

auth/feature-tests/functional/step-definitions/token.steps.ts
auth/template.yaml
auth/tests/acc/cognito-client-oidc.test.ts
auth/tests/unit/cognito-client-oidc.unit.test.ts

scope: Cognito Client
description: Updates the access token validity to the minimum that AWS will alow, 5 minutes
footer:
JIRA-ID:GOVUKAPP-1661:

config  access token validity

---

auth/project.json

[PSREDEV-XXX]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

fix: add missing acc script

---

auth/template.yaml
auth/tests/unit/cognito-throttles-cloudwatch-alarms.test.ts

[PSREDEV-XXX]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

add ConfigStackName prefix to ssm for pager-duty

---

auth/template.yaml
auth/tests/acc/cognito-throttles-cloudwatch-alarms.test.ts
auth/tests/unit/cognito-throttles-cloudwatch-alarms.test.ts

[GOVUKAPP-1506]
[GOVUKAPP-1506]: https://govukverify.atlassian.net/browse/GOVUKAPP-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: revert slack integration due to breaking path to production

---

auth/template.yaml
auth/tests/acc/cognito-throttles-cloudwatch-alarms.test.ts
auth/tests/unit/cognito-throttles-cloudwatch-alarms.test.ts

scope: CloudWatch Alarms
description: Implement integration between Slack and CloudWatch Alarms
footer:
JIRA-ID:GOVUKAPP-1761

feat  cloudwatch slack alarms

---

auth/template.yaml
auth/tests/acc/cognito-user-pool.test.ts
auth/tests/unit/cognito-client-oidc.unit.test.ts
auth/tests/unit/cognito-custom-domain.unit.test.ts
auth/tests/unit/cognito-idp.unit.test.ts
auth/tests/unit/cognito-post-authentication-lambda.unit.test.ts
auth/tests/unit/cognito-throttles-cloudwatch-alarms.test.ts
auth/tests/unit/cognito-user-pool.unit.test.ts
auth/tests/unit/cognito-waf-log-group-kms-key.unit.test.ts
auth/tests/unit/cognito-waf-log-group.unit.test.ts
auth/tests/unit/cognito-waf-logging-configuration.unit.test.ts
auth/tests/unit/cognito-waf.unit.test.ts
auth/tests/unit/cognito-web-acl-association.unit.test.ts
auth/tests/unit/shared-signals.unit.test.ts

scope: Cognito
description: Adds the plus tier to Cognito User Pool if in production to enable better auditing of user activity, unit and acc tests added. Refactor of template loading code to esnure the correct path is used for tests
JIRA-ID:GOVUKAPP-1723:

feat  add plus tier to cognito user pool if production

---

auth/package-lock.json
auth/proxy/app.ts
auth/proxy/attestation.ts
auth/proxy/config.ts
auth/proxy/firebaseJwt.ts
auth/proxy/tests/unit/config.unit.test.ts
auth/proxy/tests/unit/firebaseJwt.unit.test.ts
auth/template.yaml

Attestion JWT validation
https://govukverify.atlassian.net/browse/GOVUKAPP-1672

1672: Attestion JWT validation

---

auth/template.yaml
auth/tests/unit/cognito-custom-domain.unit.test.ts

Custom domain hardcoding removal
footer: 1818
JIRA-ID:GOVUKAPP-1818:
https://govukverify.atlassian.net/browse/GOVUKAPP-1818

refactor  removing hardcoding of custom domain

---

auth/template.yaml
auth/tests/acc/cognito-post-authentication-lambda.test.ts
auth/tests/unit/shared-signals.unit.test.ts

This PR disables any Shared Signals related artefacts from being deployed into Production
[GOVUKAPP-1888]
[GOVUKAPP-1888]: https://govukverify.atlassian.net/browse/GOVUKAPP-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: disable shared-signals

---

auth/template.yaml
auth/tests/unit/cognito-custom-domain.unit.test.ts

Closes: GOVUKAPP-1916
Code refactoring and improvement
https://govukverify.atlassian.net/browse/GOVUKAPP-1916

Feature: Custom domain refactoring

---

auth/template.yaml
auth/tests/int/shared-signals.test.ts

scope: shared signal test suite disabling
Description: Disable shared signal test suite for now
footer:
JIRA-ID:GOVUKAPP-1888:

Disable shared signal test suite for now

---

auth/template.yaml
auth/tests/unit/cognito-client-oidc.unit.test.ts
auth/tests/unit/cognito-idp.unit.test.ts

[GOVUKAPP-2004](https://govukverify.atlassian.net/browse/GOVUKAPP-2004)
[GOVUKAPP-2004]: https://govukverify.atlassian.net/browse/GOVUKAPP-2004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: update OL production urls

---

auth/template.yaml

[PSREDEV-XXX]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

Chore test prod release 2

---

auth/template.yaml

[PSREDEV-XXX]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

Testing push to production

---

.github/workflows/publish.yaml

- needed to support the opening of the production pipeline
[PSREDEV-XXX]
**_Comment:_**
**_Comment:_**
**_Comment:_**
**_Comment:_**

Chore: add promotion from build to staging

---

.secrets.baseline
auth/package-lock.json
auth/template.yaml
auth/tests/acc/attestation-cloudwatch-alarms.test.ts
auth/tests/acc/cognito-throttles-cloudwatch-alarms.test.ts
auth/tests/unit/attestation-cloudwatch-alarms.test.ts
auth/tests/unit/cognito-throttles-cloudwatch-alarms.test.ts

Runbooks link refactor and test cases
GOVUKAPP-1955

refactor  runbook links update and test cases

---

chat/package-lock.json
chat/package.json
chat/project.json
chat/tests/acc/hello-world.test.ts
chat/tests/unit/hello-world.unit.test.ts
chat/tsconfig.json
chat/vitest.config.ts
package-lock.json
package.json

Adds the `chat` directory/nx workspace for future work around the chat api integration
[GOVUKAPP-2082]
[GOVUKAPP-2082]: https://govukverify.atlassian.net/browse/GOVUKAPP-2082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add skeleton chat nx workspace

---

auth/template.yaml
auth/tests/acc/cognito-client-oidc.test.ts
auth/tests/unit/cognito-client-oidc.unit.test.ts

scope:
description: changing from 1 day to 7 days
footer:
JIRA-ID:GOVUKAPP-2135:

GOVUKAPP-2135: Refactor changing refresh token validity to 7 days

---

auth/template.yaml
auth/tests/acc/cognito-client-oidc.test.ts
auth/tests/unit/cognito-client-oidc.unit.test.ts

scope:
description: merging hotfix to main
footer:
JIRA-ID:GOVUKAPP-2135:

refactor  merging hotfix to main

---

auth/tests/driver/waf.driver.ts

scope:
description: restoring file
footer:
JIRA-ID:GOVUKAPP-:

Chore: restoring waf driver file

---

chat/template.yaml
chat/tests/infra/api-gateway-waf.unit.test.ts
chat/tests/infra/api-gateway.unit.test.ts

This PR introduces the WAF for the Chat Api Gateway, which introduces rules `AWSManagedRulesKnownBadInputsRuleSet` and `RateLimitRule`
[GOVUKAPP-2111]
[GOVUKAPP-2111]: https://govukverify.atlassian.net/browse/GOVUKAPP-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: waf for api gateway, part 1 (no acc tests)

---

auth/tests/acc/shared-signals-receiver.test.ts

Skipping feature flag on the pipeline

Feat: Skip feature flag test on the pipeline

---

auth/template.yaml

This PR gives a FunctionName to the `PagerDutyTestFunction` resource in `auth` so that we have a consistent way of referencing it from other stacks.
[GOVUKAPP-2110]

chore: FunctionName for PagerDutyTestFunction

---

chat/README.md

chore: update README.md for chat

---

auth/shared-signal-receiver/config/index.ts
auth/shared-signal-receiver/signature-verification/fetch-jwks.ts
auth/shared-signal-receiver/signature-verification/verify-signature.ts
auth/shared-signal-receiver/tests/unit/config/index.unit.test.ts
auth/shared-signal-receiver/tests/unit/signature-verification/fetch-jwks.unit.test.ts
auth/shared-signal-receiver/tests/unit/signature-verification/verify-signature.unit.test.ts
auth/template.yaml
auth/tests/acc/shared-signals-receiver.test.ts
auth/tests/driver/shared-signals.driver.ts
auth/tests/performance/dataloader/sharedSignals.js
auth/tests/performance/dataloader/signPayload.js

scope: shared-signals
description: use rs256 as key alg
footer: 2280
JIRA-ID:GOVUKAPP-2280:

feat  shared-signals use rs256 alg

---

auth/template.yaml

chore: update runbook links

---

auth/shared-signal-receiver/errors.ts
auth/shared-signal-receiver/handler.ts
auth/shared-signal-receiver/response.ts
auth/shared-signal-receiver/signature-verification/verify-signature.ts
auth/shared-signal-receiver/tests/unit/handler.unit.test.ts
auth/shared-signal-receiver/tests/unit/signature-verification/verify-signature.unit.test.ts
auth/tests/acc/shared-signals-receiver.test.ts

To align with SET errors
GOVUKAPP-2404

error responses: To align with SET errors

---

services/auth/proxy/jwk-cache.ts
services/auth/proxy/proxy.ts
services/auth/proxy/tests/unit/jwk-cache.test.ts
services/auth/shared-signal-health-check/service/health-check-service.ts
services/auth/shared-signal-health-check/tests/unit/service/health-check-service.unit.test.ts
services/auth/template.yaml

Timeouts functionality
GOVUKAPP-1819

Feat: Timeouts functionality

---

services/chat/template.yaml
services/chat/tests/infra/api-gateway-waf-log-group.unit.test.ts
services/chat/tests/infra/api-gateway.unit.test.ts

[GOVUKAPP-2444
](https://govukverify.atlassian.net/browse/GOVUKAPP-2444)

feat: make chat logs retention period to be configurable

---

services/auth/template.yaml
services/auth/tests/unit/shared-signals.unit.test.ts

[GOVUKAPP-2438
](https://govukverify.atlassian.net/browse/GOVUKAPP-2438)

feat: enable shared signals in production
